name: Build PDF from Text

on:
  push:
    paths:
      - "README.md"
  workflow_dispatch:


jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run LaTeX in Docker
      uses: addnab/docker-run-action@v3
      with:
        image: texlive/texlive:latest
        options: --rm
        run: |
          tlmgr install babel-russian
          pdflatex -interaction=nonstopmode output.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: built-pdf
        path: output.pdf
