name: Build PDF from Text

on:
  push:
    paths:
      - "README.md"

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive texlive-latex-extra

    - name: Convert text to LaTeX
      run: |
        python3 convert_to_latex.py README.md output.tex

    - name: Build PDF
      run: pdflatex output.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: built-pdf
        path: output.pdf
